name: Push to ECR

on:
  push:
    branches:
      - main

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Testing
        run: |
            echo "Testing New Relic"

    #   - name: Log in to Amazon ECR
    #     id: login-ecr
    #     uses: aws-actions/amazon-ecr-login@v1

    #   - name: Build, tag, and push image to ECR
    #     env:
    #       ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    #       IMAGE_NAME: my-app
    #     run: |
    #       docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
    #       docker push $ECR_REGISTRY/$IMAGE_NAME:latest
