name: deploy image to app runner

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      # app:
      #   required: true
      #   type: string
# permissions:
#   id-token: write
#   contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_INFRA_DEPLOYER_ROLE }}
      #     aws-region: ${{ vars.AWS_REGION }}
      #     role-session-name: fs-infra-configs-deployer-github-actions-${{ github.job }}
