name: Push to ECR

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Testing
        run: |
            echo "Testing New Relic"
            echo "Another test"
            envsubst < .env.example > .env
            cat .env.example
            echo "real one"
            echo "This is the VAR1: ${VAR1}"
            cat .env
