name: Push to ECR

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Testing
        env:
            VAR1: ${{ vars.VAR1 }}
        run: |
            echo "Testing New Relic"

            echo -e "\n\nFIRST ONE\n\n"
            ls
            envsubst < .env.example > .env

            echo -e "\n\nSECOND ONE\n\n"
            ls

            # cat Dockerfile
            # envsubst < Dockerfile > Dockerfile
            # echo -e "\nSECOND ONE"
            # ls
            # cat Dockerfile