name: Push to ECR

on:
  push:
    branches:
      - main

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    #   - name: Testing
    #     run: |
    #         echo "Testing New Relic"
    #         echo "Another test"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_INFRA_DEPLOYER_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: fs-infra-configs-deployer-github-actions-${{ github.job }}

    #   - name: Build, tag, and push image to ECR
    #     env:
    #       ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
    #       IMAGE_NAME: my-app
    #     run: |
    #       docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
    #       docker push $ECR_REGISTRY/$IMAGE_NAME:latest
