name: Push to ECR

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Testing
        env:
            VAR1: ${{ vars.VAR1 }}
        run: |
            echo "Testing New Relic"

            envsubst < .env.example > .env
            cat Dockerfile
            envsubst < Dockerfile > Dockerfile
            echo "SECOND ONE"
            ll
            cat Dockerfile